version: '3'

services:
  gallery:
    build: .
    depends_on:
      - 'database'
    ports:
      - '80:3001'

  database:
    image: mysql:5.7
    MYSQL_DATABASE: PhotoGallery
    MYSQL_USER: root
    
